/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    // All imagery is local now — generated by scripts/ and committed as WebP —
    // so Next can optimise it. `unoptimized: true` and the Pexels remotePattern
    // were a workaround for hot-linking a photo CDN the sandbox couldn't reach.
    formats: ['image/avif', 'image/webp'],
  },
  async redirects() {
    // Capability aliases → existing service pages. Config-level redirects emit
    // a proper Location header in production (page-level redirect() in a
    // statically generated route returned a 307 with no Location, breaking
    // navigation on deployed builds).
    return [
      { source: '/services/brand', destination: '/services/branding', permanent: false },
      { source: '/services/digital', destination: '/services/web-design', permanent: false },
      { source: '/services/product', destination: '/services/ui-ux-design', permanent: false },
      { source: '/services/code', destination: '/services/frontend-development', permanent: false },
      { source: '/services/motion', destination: '/services/motion-design', permanent: false },
      // /studio was an unreplaced template page — a beverage brand's landing
      // page, complete with "Shop Now" and two invented "Verified Buyer"
      // testimonials — sitting in the primary nav. /about is the real studio
      // page, so the nav's "Studio" link now lands there.
      { source: '/studio', destination: '/about', permanent: false },
      // Latent internal-link typos that previously 404'd
      { source: '/services/ui-ux', destination: '/services/ui-ux-design', permanent: true },
      { source: '/services/frontend-dev', destination: '/services/frontend-development', permanent: true },
    ];
  },
};

export default nextConfig;
