// Writes src/lib/image-dims.ts: the width and height of every picture in
// public/images, so pictures can be laid out (and sized by <Pic>) before
// they load. Run after adding or changing pictures: npm run images:dims
import { readdir, writeFile } from "node:fs/promises";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const root = fileURLToPath(new URL("../public/", import.meta.url));
const dir = join(root, "images");

async function* walk(d) {
  for (const e of await readdir(d, { withFileTypes: true })) {
    const p = join(d, e.name);
    if (e.isDirectory()) yield* walk(p);
    else if (/\.(webp|avif|png|jpe?g)$/i.test(e.name)) yield p;
  }
}

const dims = {};
for await (const file of walk(dir)) {
  const { width, height } = await sharp(file).metadata();
  dims["/" + relative(root, file).split(sep).join("/")] = [width, height];
}
const sorted = Object.fromEntries(Object.entries(dims).sort(([a], [b]) => a.localeCompare(b)));
const body = Object.entries(sorted)
  .map(([k, [w, h]]) => `  "${k}": [${w}, ${h}],`)
  .join("\n");
await writeFile(
  new URL("../src/lib/image-dims.ts", import.meta.url),
  `// Generated by scripts/image-dims.mjs (npm run images:dims). Do not edit.\n/** Width and height of each picture in /public/images. */\nexport const IMAGE_DIMS: Record<string, readonly [number, number]> = {\n${body}\n};\n`,
);
console.log(`image-dims: ${Object.keys(sorted).length} pictures`);
