import brandAssets from "@/lib/brand-assets.json";
import { cn } from "@/lib/utils";

const ASSETS = brandAssets as Record<string, string | null>;

/**
 * The Greene marks.
 *
 * Prefers the real logo exports prepared by `npm run brand`; falls back to the
 * hand-drawn SVGs in public/brand until those exist, so the site never renders
 * a broken image while the assets are being swapped over.
 *
 * The prepared PNGs are alpha masks rather than coloured artwork, painted with
 * `background: currentColor` through `mask-image`. That is what lets a raster
 * export behave like the SVGs it replaces — one file that takes the colour of
 * whatever surface it sits on, in either theme, with no white box on dark.
 */
function Mark({
  src,
  label,
  className,
  style,
}: {
  src: string;
  label: string;
  className?: string;
  style?: React.CSSProperties;
}) {
  // SVGs that already use currentColor can be rendered directly; masks cannot.
  const isMask = src.endsWith(".png");

  if (!isMask) {
    return (
      // eslint-disable-next-line @next/next/no-img-element
      <img
        src={src}
        alt={label}
        className={cn("object-contain", className)}
        style={style}
      />
    );
  }

  return (
    <span
      role="img"
      aria-label={label}
      className={className}
      style={{
        display: "inline-block",
        backgroundColor: "currentColor",
        WebkitMaskImage: `url(${src})`,
        maskImage: `url(${src})`,
        WebkitMaskRepeat: "no-repeat",
        maskRepeat: "no-repeat",
        WebkitMaskPosition: "center",
        maskPosition: "center",
        WebkitMaskSize: "contain",
        maskSize: "contain",
        ...style,
      }}
    />
  );
}

/**
 * The GS monogram, mirrored as JSX.
 *
 * Generated by `npm run monogram` (outfit-700-tight: Outfit, 700, -0.03em)
 * and kept on disk at /brand/gs-monogram-outfit.svg. The paths are the font's
 * own outlines, not a trace.
 *
 * It is inlined rather than loaded through <img> for the same reason the six
 * concept marks are mirrored in BrandMark.tsx: an SVG loaded as an image is an
 * isolated document, so `currentColor` resolves against nothing and the mark
 * paints black — a near-invisible smudge on the dark theme. Inline, it takes
 * the colour of whatever surface it sits on, which is the whole contract.
 */
function MonogramGlyphs({
  label,
  className,
  style,
}: {
  label: string;
  className?: string;
  style?: React.CSSProperties;
}) {
  return (
    <svg
      viewBox="0 0 1421.5 1421.5"
      fill="currentColor"
      role="img"
      aria-label={label}
      className={cn("shrink-0", className)}
      style={style}
    >
      <g transform="translate(49 1063.75) scale(1 -1)">
        <path d="M401 -12Q323 -12 255.5 16.5Q188 45 138 95Q88 145 59.5 211Q31 277 31 354Q31 432 60 497.5Q89 563 141 612.5Q193 662 261.5 690Q330 718 409 718Q500 718 575 684.5Q650 651 699 593L591 485Q558 529 511.5 551.5Q465 574 408 574Q346 574 297 546.5Q248 519 220.5 469.5Q193 420 193 354Q193 289 220 239Q247 189 294 160.5Q341 132 402 132Q463 132 506.5 155.5Q550 179 573.5 224Q597 269 597 332L702 262L387 267L387 400L758 400L758 377Q758 251 712.5 164Q667 77 586.5 32.5Q506 -12 401 -12Z" transform="translate(0 0)" />
        <path d="M280 -11Q192 -11 129.5 17Q67 45 16 103L118 205Q152 166 193.5 144.5Q235 123 290 123Q339 123 366.5 141.5Q394 160 394 192Q394 220 376.5 238Q359 256 329 269Q299 282 264 293.5Q229 305 193.5 321Q158 337 128.5 360Q99 383 81 419Q63 455 63 508Q63 574 94.5 621Q126 668 183 692.5Q240 717 312 717Q387 717 448 691Q509 665 549 621L446 518Q414 551 381.5 567Q349 583 309 583Q268 583 244 567.5Q220 552 220 523Q220 497 238 480.5Q256 464 285.5 452Q315 440 350.5 428Q386 416 421.5 400.5Q457 385 486 360Q515 335 533.5 298Q552 261 552 205Q552 104 480 46.5Q408 -11 280 -11Z" transform="translate(740.5 0)" />
      </g>
    </svg>
  );
}

/** The compact GS monogram — nav, footer chip, anywhere square. */
export function GreeneMonogram({
  className,
  size = 36,
  /** Ignore `size` and fill the parent instead. */
  fill = false,
}: {
  className?: string;
  size?: number;
  fill?: boolean;
}) {
  const src = ASSETS["gs-mark"];
  const style = fill ? undefined : { width: size, height: size };

  // The prepared export wins the moment it exists; until then the monogram
  // picked off the contact sheet stands in, rather than the older chip.
  if (!src) {
    return <MonogramGlyphs label="Greene Studios" className={cn("shrink-0", className)} style={style} />;
  }

  return (
    <Mark
      src={src}
      label="Greene Studios"
      className={cn("shrink-0", className)}
      style={style}
    />
  );
}

/** The stacked "Greene Studios" wordmark — lockups and larger moments. */
export function GreeneWordmark({
  className,
  width = 180,
}: {
  className?: string;
  width?: number;
}) {
  const src = ASSETS["greene-wordmark"] ?? "/brand/greene-stacked.svg";
  return (
    <Mark
      src={src}
      label="Greene Studios"
      className={className}
      style={{ width, aspectRatio: "16 / 9" }}
    />
  );
}

/** Whether the real exports are in place yet. */
export const hasBrandExports = Boolean(ASSETS["gs-mark"]);
